# Core
db:
  redis:
    emulate: true
    namespace: EG

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config' 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  tokenType: 'jwt'
  timeToExpiry: 7200000
  secretOrPublicKey: ${SIGN_KEY:-'669B523BBC1157221D3AAA35E8398'}
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
